from typing import Protocol, Any, Mapping

class DatabaseConnector(Protocol):
    async def execute(self, query: str, params: Mapping[str, Any] | None = None) -> None: ...
    async def executescript(self, script: str) -> None: ...
    async def fetch_one(self, query: str, params: Mapping[str, Any] | None = None) -> Mapping[str, Any] | None: ...
    async def close(self) -> None: ...
    
    @property
    def dialect(self) -> str: ...